@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title C4. Context. Умный дом.

' Пользователи системы
Person(user, "Пользователь", "Владелец дома")
Person(spec, "Специалист", "Специалист компании")

' Система Умный дом
System(smart_home, "Управление отоплением", "Приложение для управления отоплением в доме и получения температурных данных с устройств в доме")

' Внешняя система
System_Ext(ext_api, "API датчиков температуры", "Получение температурных данных")

' База данных
SystemDb(database, "База данных", "PostgreSQL. Информация о датчиках и их данных")

' Связи между компонентами
Rel(user, smart_home, "Просмотр температуры, включение/выключение отопления", "Веб-интерфейс")
Rel(spec, smart_home, "Добавление новых датчиков", "Веб-интерфейс")
Rel(smart_home, database, "Сохранение и получение данных", "SQL")
Rel(smart_home, ext_api, "Получение температурных данных", "API")

@enduml